[tool.poetry]
name = "firefox-translations-training"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pip-tools = "^7.3.0"

[tool.poetry.group.black.dependencies]
black = "^23.7.0"

[tool.poetry.group.lint.dependencies]
ruff = "^0.0.287"

[tool.poetry.group.opuscleaner.dependencies]
# use the latest main, 0.3.1 conflicts with OpusTrainer
opuscleaner = {git = "https://github.com/hplt-project/OpusCleaner.git", rev="24014c47200cf78aa4d1ba001df24c31f554b1b9"}

[tool.poetry.group.taskcluster.dependencies]
taskcluster = "^56.0.3"

[tool.poetry.group.tensorboard.dependencies]
marian-tensorboard = "^0.2.1"

[tool.poetry.group.utils.dependencies]
sacrebleu="2.0.0"
mtdata="0.3.2"
requests="2.26.0"
humanize = "^4.9.0"

[tool.poetry.group.tests.dependencies]
sacrebleu="2.0.0"
mtdata="0.3.2"
requests="2.26.0"
pytest="7.4.3"
# use the latest main, switch to PyPi when released
opustrainer = {git = "https://github.com/hplt-project/OpusTrainer.git", rev="9133e1525c7ee37f53ea14ee6a180152bf7ea192"}
pytest-clarity = "^1.0.1"
requests-mock = "^1.11.0"
sh = "^2.0.6"
zstandard = "^0.22.0"

[tool.black]
extend-exclude= "/3rd_party"
line-length = 99

# Match the rules from mozilla-central.
# https://searchfox.org/mozilla-central/source/pyproject.toml
[tool.ruff]
line-length = 99
# See https://beta.ruff.rs/docs/rules/ for a full list of rules.
select = [
  "E", "W",    # pycodestyle
  "F",         # pyflakes
  "I",         # isort
  "PL",        # pylint
]
ignore = [
  # These are intentionally ignored.
  "E741",      # ambiguous-variable-name
  "PLR09",     # too-many-return-statements, too-many-branches, too-many-arguments, too-many-statements
  "PLR2004",   # magic-value-comparison

  # These are handled by black.
  "E1", "E4", "E5", "W2", "W5"
]
exclude = [
  "3rd_party"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
