verbose: false
use-conda: true
resources: gpu=8
cores: all
cache: false
reason: true
config:
  # install dependencies on a local machine
  - deps=true
  # root path to a folder with data, models and logs
  - root=/data
  - cuda=/usr/local/cuda
  - cudnn=/cudnn
  # how much memory Marian reserves on a GPU
  - workspace=12000
  # a number of GPUs you want to use
  - numgpus=4
  - mariancmake=""
  # (optional) override available GPU ids, example gpus=0 2 5 6
  - gpus=""