datasets:
  original: <dataset0> # Original parallel corpus

stages:
  - train

train:
  - original 1.0
  - until original 10 # Train for 10 epochs. Only OpusTrainer can control epochs, it's all one big epoch for Marian

modifiers:
- UpperCase: 0.1 # Apply randomly to 5% of sentences
- TitleCase: 0.1
#- Typos: 0.05

seed: 1111
num_fields: 2
