datasets:
  original: <dataset0> # Original parallel corpus

stages:
  - train

train:
  - original 1.0
  - until original inf # General training until marian early stops

# TODO: augment corpus before decoding or reduce augmentation rate
# TODO: https://github.com/mozilla/firefox-translations-training/issues/272
modifiers:
- UpperCase: 0.07 # Apply randomly to 7% of sentences
- TitleCase: 0.05
# TODO: enable typos, issue https://github.com/mozilla/firefox-translations-training/issues/262
#- Typos: 0.05
# TODO: enable tags, currently doesn't work because of the issue with  tokenization
# TODO: https://github.com/mozilla/firefox-translations-training/issues/261
#- Tags: 0.05
#  augment: 0.05
#  replace: 0.05
#  spm_vocab: <vocab>

seed: 1111
# parallel sentences + token alignments
num_fields: 3
